    def move(self,keys,obstacles):
        #...
                if self.can_move(obstacles, "up"):
                #...
                if self.can_move(obstacles, "down"):
                #...
                if self.can_move(obstacles, "left"):
                #...
                if self.can_move(obstacles, "right"):
